### ISSUE TITLE
Publish Tool As Standalone EXE

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/BetterStrings#3]
Configure the app to publish to a folder as `btrstr.exe`

**Comment by matthiasjost** [comment]
@ardalis I tried different things I ended up changing the Project file and publishing XML. I tried it with post XML commands. See here: https://curia.me/visual-studio-add-post-publish-script/ But it did not work for me.

https://github.com/DevBetterCom/BetterStrings/tree/matthias/publish-as-standalone-exe

**Comment by matthiasjost** [comment]
I solved it just by changing the Assembly Name.
